# -*- coding: utf-8 -*-
"""Copy of c82.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PosdZBEDaM7JgftX7iICmjvLsPsnLPW
"""

import pickle
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

filename = 'decision_tree_model_Heart.pkl'
with open(filename, 'rb') as file:
    loaded_model = pickle.load(file)

# creating the streamlit app
st.title('Heart Failure prediction app')
st.subheader('Please enter your data:')

# data loading and preprocessing
df = pd.read_csv('features.csv')
columns_list = df.columns.to_list()

uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)



    prediction = loaded_model.predict(df)
    prediction_text = np.where(prediction == 1, 'Yes', 'No')
    st.subheader('Heart failure:')
    st.write(prediction_text)